JSON_MACHINE = [
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a4246",
        "source": "PC_VP_LaserCutFinalTrim_1_Left_Conveyor",
        "source_clean": "Station CV-L VP-001",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a4248",
        "source": "PC_VP_LaserCutFinalTrim_1_Right_Conveyor",
        "source_clean": "Station CV-R VP-001",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a424b",
        "source": "PC_VP_LaserCutFinalTrim_2_Left_Conveyor",
        "source_clean": "Station CV-L VP-002",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a424d",
        "source": "PC_VP_LaserCutFinalTrim_2_Right_Conveyor",
        "source_clean": "Station CV-R VP-002",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a424f",
        "source": "PC_VP_LaserCutFinalTrim_3_Left_Conveyor",
        "source_clean": "Station CV-L VP-003",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a4251",
        "source": "PC_VP_LaserCutFinalTrim_3_Right_Conveyor",
        "source_clean": "Station CV-R VP-003",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "67507c18a0c9f1bb200a424f",
        "source": "PC_VP_LaserCutFinalTrim_4_Left_Conveyor",
        "source_clean": "Station CV-L VP-004",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "77507c18a0c9f1bb200a4251",
        "source": "PC_VP_LaserCutFinalTrim_4_Right_Conveyor",
        "source_clean": "Station CV-R VP-004",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "56e210ffb08b5449d4abd643",
        "source": "PC_VP_LaserCutRollFed_1",
        "source_clean": "1221-ALCR-V1-PC-VP-001",
        "source_type": "LaserCutRollFed",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "56e210ffb08b5449d4abd644",
        "source": "PC_VP_LaserCutRollFed_2",
        "source_clean": "1221-ALCR-V1-PC-VP-002",
        "source_type": "LaserCutRollFed",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "56e210ffb08b5449d4abd645",
        "source": "PC_VP_LaserCutRollFed_3",
        "source_clean": "1221-ALCR-V1-PC-VP-003",
        "source_type": "LaserCutRollFed",
    },
    {
        "factory_location": "VP",
        "factory_partner": "PC",
        "id": "176bdab28f5a11e6b0cc28d2",
        "source": "PC_VP_LaserCutRollFed_4",
        "source_clean": "1221-ALCR-V1-PC-VP-004",
        "source_type": "LaserCutRollFed",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "579f6f051d41c8563857a900",
        "metadata": {
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_AutoNoSew_1_Left_Conveyors",
        "source_clean": "NoSew_Cell_L_Conveyors_VY-001",
        "source_type": "AutoNoSew_Conveyors",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "579f6f051d41c8563857a901",
        "metadata": {
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_AutoNoSew_1_Left_Robot1",
        "source_clean": "NoSew_Cell_L_Robot1_VY-001",
        "source_type": "AutoNoSew_Robot1",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "579f6f051d41c8563857a902",
        "metadata": {
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_AutoNoSew_1_Left_Robot2",
        "source_clean": "NoSew_Cell_L_Robot2_VY-001",
        "source_type": "AutoNoSew_Robot2",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "579f6f051d41c8563857a903",
        "metadata": {
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_AutoNoSew_1_Right_Conveyors",
        "source_clean": "NoSew_Cell_R_Conveyors_VY-001",
        "source_type": "AutoNoSew_Conveyors",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "579f6f051d41c8563857a904",
        "metadata": {
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_AutoNoSew_1_Right_Robot1",
        "source_clean": "NoSew_Cell_R_Robot1_VY-001",
        "source_type": "AutoNoSew_Robot1",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "579f6f051d41c8563857a905",
        "metadata": {
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_AutoNoSew_1_Right_Robot2",
        "source_clean": "NoSew_Cell_R_Robot2_VY-001",
        "source_type": "AutoNoSew_Robot2",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "56e210ffb08b5449d4abd646",
        "source": "PC_VY_AutoRubber_1",
        "source_clean": "1215-ARBS-10DL-PC-VY-001",
        "source_type": "AutoRubber",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a4253",
        "source": "PC_VY_LaserCutFinalTrim_1_Left_Conveyor",
        "source_clean": "Station CV-L VY-001",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a4255",
        "source": "PC_VY_LaserCutFinalTrim_1_Right_Conveyor",
        "source_clean": "Station CV-R VY-001",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a4258",
        "source": "PC_VY_LaserCutFinalTrim_2_Left_Conveyor",
        "source_clean": "Station CV-L VY-002",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "57507c18a0c9f1bb200a425a",
        "source": "PC_VY_LaserCutFinalTrim_2_Right_Conveyor",
        "source_clean": "Station CV-R VY-002",
        "source_type": "LaserCutFinalTrim_Conveyor",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "568fc8be1d41c81cb820a1b2",
        "metadata": {
            "etl_enabled": True,
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_OscillatingKnife_1",
        "source_clean": "1207-OKC-CZXL-PC-VY-001",
        "source_type": "OscillatingKnife",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "568fc8be1d41c81cb820a1b3",
        "metadata": {
            "etl_enabled": True,
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_OscillatingKnife_2",
        "source_clean": "1207-OKC-CZXL-PC-VY-002",
        "source_type": "OscillatingKnife",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "568fc8be1d41c81cb820a1b4",
        "metadata": {
            "etl_enabled": True,
            "local_to_utc_convert_flag": False,
            "timezone": "Asia/Ho_Chi_Minh",
        },
        "source": "PC_VY_OscillatingKnife_3",
        "source_clean": "1207-OKC-CZXL-PC-VY-003",
        "source_type": "OscillatingKnife",
    },
    {
        "factory_location": "VY",
        "factory_partner": "PC",
        "id": "5727b6031d41c831ecce0246",
        "source": "PC_VY_UpperComponentBacking_1",
        "source_clean": "1224-UCB-V1-PC-VY-001",
        "source_type": "UpperComponentBacking",
    },
]

MACHINE_TYPE =[
            {
                'type': 'float',
                'name': 'stat__test_float',
                'title_prefix': 'test float'
            },
            {
               'type': 'string', 
               'name': 'stat__test_string',
               'title_prefix': 'test string'
            },
            {
               'type': 'string', 
               'name': 'stat__test_hidden',
                'title_prefix': 'test hidden',
                'ui_hidden' : True
            }
        ]
