AVALIBLE_COOKBOOK_JSON=[{'hash': '64hujs5ffb40124475e15d9852ba7e69be121a6b435eae4879392acc970f80f8', 'tag': 'demo', 'auto_generated_parent': {}, 'name': 'Test cookbook', 'assetNames': ['asset_test'], 'key_constraint': {'field': {'fieldName': 'stats__Cylinders__val', 'machineId': 'e2mj2b4f215b2323f45d04fa2', 'machineName': 'asset_test', 'machineDisplayName': 'Asset - test', 'fieldType': 'categorical', 'machineType': 'Diecast', 'fieldDisplayName': 'Cylinders', 'fieldUnit': ''}, 'valueMap': {'4': 1, '6': 0}}, 'recipe_groups': [{'id': 'DJy4jyEEi', 'values': ['6'], 'runBoundaries': [], 'maxDuration': {'isEnabled': False, 'minimum': 0, 'unit': 'second'}, 'topRun': 10, 'constraints': [], 'levers': [{'fieldName': 'stats__AluminumTempAvg__val', 'machineId': 'e2df2b4f876b763f45d04se2', 'machineName': 'asset_test', 'machineDisplayName': 'Asset-Test', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'AluminumTemp - Average', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__AluminumTempMax__val', 'machineId': 'asfdalkfjlkfji', 'machineName': 'asset_test', 'machineDisplayName': 'Asset - test', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'AluminumTemp - Max', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__DieTemp__val', 'machineId': '435tsfrdsvxcvr', 'machineName': 'asset_test', 'machineDisplayName': 'asset - test', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Die Temperature', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__InjectionCurveDifference__val', 'machineId': 'sfawrfefasf', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Curve Difference', 'fieldUnit': 'pascal'}, {'fieldName': 'stats__InjectionPressureMax__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Pressure Max', 'fieldUnit': 'pascal'}, {'fieldName': 'stats__InjectionPressureMin__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Pressure Min', 'fieldUnit': 'pascal'}], 'outcomes': [{'field': {'fieldName': 'quality', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'kpi', 'machineType': 'Diecast', 'fieldDisplayName': 'Quality'}, 'weight': 1, 'optimization_func': 'maximize'}], 'filters': {'duration': {'isEnabled': False, 'minimum': 0, 'unit': 'second'}, 'recordFilters': []}, 'dateRange': {'value': {'relativeAmount': 7, 'relativeUnit': 'day'}, 'config': {'mode': 'relative', 'selectableRelativeUnits': ['minute', 'hour', 'day', 'week', 'month', 'year'], 'enableTimeTypeSelection': True, 'showQuarterShortcuts': True}}, 'computeDeployedDateRange': None, 'statsCalculationSetting': 'default', 'deployed': {'id': 'SJy4jyFFi', 'values': ['6'], 'runBoundaries': [], 'maxDuration': {'isEnabled': False, 'minimum': 0, 'unit': 'second'}, 'topRun': 10, 'constraints': [], 'levers': [{'fieldName': 'stats__AluminumTempAvg__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'AluminumTemp - Average', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__AluminumTempMax__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'AluminumTemp - Max', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__DieTemp__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Die Temperature', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__InjectionCurveDifference__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Curve Difference', 'fieldUnit': 'pascal'}, {'fieldName': 'stats__InjectionPressureMax__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Pressure Max', 'fieldUnit': 'pascal'}, {'fieldName': 'stats__InjectionPressureMin__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Pressure Min', 'fieldUnit': 'pascal'}], 'outcomes': [{'field': {'fieldName': 'quality', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'kpi', 'machineType': 'Diecast', 'fieldDisplayName': 'Quality'}, 'weight': 1, 'optimization_func': 'maximize'}], 'filters': {'duration': {'isEnabled': False, 'minimum': 0, 'unit': 'second'}, 'recordFilters': []}, 'dateRange': {'value': {'relativeAmount': 7, 'relativeUnit': 'day'}, 'config': {'mode': 'relative', 'selectableRelativeUnits': ['minute', 'hour', 'day', 'week', 'month', 'year'], 'enableTimeTypeSelection': True, 'showQuarterShortcuts': True}}, 'computeDeployedDateRange': None, 'statsCalculationSetting': 'default', 'deployed_date': '2023-01-20T17:02:06.797Z', 'deployed_status': {'success': True, 'run_count_saved': 10215, 'seconds_to_exec': 5874, 'timestamp': '2023-03-21 03:59:54.633000'}}}, {'constraints': [], 'levers': [{'fieldName': 'stats__AluminumTempAvg__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'AluminumTemp - Average', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__AluminumTempMax__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'AluminumTemp - Max', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__DieTemp__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Die Temperature', 'fieldUnit': 'celsius'}, {'fieldName': 'stats__InjectionCurveDifference__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Curve Difference', 'fieldUnit': 'pascal'}, {'fieldName': 'stats__InjectionPressureMax__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Pressure Max', 'fieldUnit': 'pascal'}, {'fieldName': 'stats__InjectionPressureMin__val', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'continuous', 'machineType': 'Diecast', 'fieldDisplayName': 'Injection Pressure Min', 'fieldUnit': 'pascal'}], 'outcomes': [{'field': {'fieldName': 'quality', 'machineId': 'e2df2b4f115b763f45d04fa2', 'machineName': 'JB_HM_Diecast_1', 'machineDisplayName': 'Hamilton - Diecast 1', 'fieldType': 'kpi', 'machineType': 'Diecast', 'fieldDisplayName': 'Quality'}, 'weight': 1, 'optimization_func': 'maximize'}], 'dateRange': {'value': {'relativeAmount': 7, 'relativeUnit': 'day'}, 'config': {'mode': 'relative', 'selectableRelativeUnits': ['minute', 'hour', 'day', 'week', 'month', 'year'], 'enableTimeTypeSelection': True, 'showQuarterShortcuts': True}}, 'filters': {'duration': {'isEnabled': False, 'minimum': 0, 'unit': 'second'}, 'recordFilters': []}, 'runBoundaries': [], 'maxDuration': {'isEnabled': False, 'minimum': 0, 'unit': 'second'}, 'topRun': 10, 'computeDeployedDateRange': None, 'statsCalculationSetting': 'default', 'id': 'ByxJEiJFKj', 'values': ['4']}], 'metadata': {'created_by': {'id': '5a1c9f9798214579dacc917a', 'email': 'ahome@sightmachine.com', 'metadata': {'first_name': 'Andrew', 'last_name': 'Home', 'tenant': 'demo'}}}, 'updatetime': '2023-03-21 03:59:54.634000', 'assets': [], 'id': 'liafalkfjdlak'}]
RUNS = {'runs':[
    {'_count': 12,
 '_count_muted': 0,
 '_duration_seconds': 649.0,
 '_earliest': '2022-10-21T00:35:32+00:00',
 '_latest': '2022-10-21T00:46:21+00:00',
 '_score': 1.0,
 'constraint_group_id': '0',
 'constraints': [],
 'cookbook': '63ab6b263fa4880c06334b03',
 'filters': [],
 'i_vals': [{'asset': 'SHARED', 'name': 'group', 'value': '0'},
            {'asset': 'SHARED', 'name': 'sequence', 'value': 2}],
 'levers': [{'asset': 'JB_HM_Diecast_1',
             'd_pos': 2,
             'name': 'stats__AluminumTempAvg__val',
             'value': {'avg': 659.8448127439334,
                       'count': 9.0,
                       'max': 671.1048565509,
                       'min': 653.718308813,
                       'var_pop': 29.816738449355437}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 3,
             'name': 'stats__AluminumTempMax__val',
             'value': {'avg': 659.8448127439334,
                       'count': 9.0,
                       'max': 671.1048565509,
                       'min': 653.718308813,
                       'var_pop': 29.816738449355437}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 4,
             'name': 'stats__DieTemp__val',
             'value': {'avg': 290.8228674053778,
                       'count': 9.0,
                       'max': 295.2332287849,
                       'min': 284.84446548529996,
                       'var_pop': 11.993829414162574}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 5,
             'name': 'stats__InjectionCurveDifference__val',
             'value': {'avg': 1.576386980588889,
                       'count': 9.0,
                       'max': 2.8598220936,
                       'min': 0.3786822327000001,
                       'var_pop': 0.810658290414194}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 6,
             'name': 'stats__InjectionPressureMax__val',
             'value': {'avg': 39.537370569911104,
                       'count': 9.0,
                       'max': 44.0884060904,
                       'min': 35.4952094968,
                       'var_pop': 5.452849234986407}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 7,
             'name': 'stats__InjectionPressureMin__val',
             'value': {'avg': 36.76283137485556,
                       'count': 9.0,
                       'max': 38.8721003798,
                       'min': 35.0169147198,
                       'var_pop': 1.2194962602188073}}],
 'outcomes': [{'asset': 'JB_HM_Diecast_1',
               'd_pos': 0,
               'kpi': {'aggregates': {'Output': 'sum', 'ScrapQuantity': 'sum'},
                       'dependencies': {'Output': 9.0, 'ScrapQuantity': 0.0},
                       'formula': '((Output) / (Output + ScrapQuantity)) * 100 '
                                  'if ((Output + ScrapQuantity) > 0) else '
                                  'None'},
               'name': 'quality',
               'value': {'avg': 100.0,
                         'count': 100.0,
                         'max': 100.0,
                         'min': 100.0,
                         'normal': 1.0000000000000002,
                         'var_pop': 100.0}}]}
],
 'constraint_group':[{'_count': 12,
 '_count_muted': 0,
 '_duration_seconds': 649.0,
 '_earliest': '2022-10-21T00:35:32+00:00',
 '_latest': '2022-10-21T00:46:21+00:00',
 '_score': 1.0,
 'constraint_group_id': '0',
 'constraints': [],
 'cookbook': '63ab6b263fa4880c06334b03',
 'filters': [],
 'i_vals': [{'asset': 'SHARED', 'name': 'group', 'value': '0'},
            {'asset': 'SHARED', 'name': 'sequence', 'value': 2}],
 'levers': [{'asset': 'JB_HM_Diecast_1',
             'd_pos': 2,
             'name': 'stats__AluminumTempAvg__val',
             'value': {'avg': 659.8448127439334,
                       'count': 9.0,
                       'max': 671.1048565509,
                       'min': 653.718308813,
                       'var_pop': 29.816738449355437}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 3,
             'name': 'stats__AluminumTempMax__val',
             'value': {'avg': 659.8448127439334,
                       'count': 9.0,
                       'max': 671.1048565509,
                       'min': 653.718308813,
                       'var_pop': 29.816738449355437}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 4,
             'name': 'stats__DieTemp__val',
             'value': {'avg': 290.8228674053778,
                       'count': 9.0,
                       'max': 295.2332287849,
                       'min': 284.84446548529996,
                       'var_pop': 11.993829414162574}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 5,
             'name': 'stats__InjectionCurveDifference__val',
             'value': {'avg': 1.576386980588889,
                       'count': 9.0,
                       'max': 2.8598220936,
                       'min': 0.3786822327000001,
                       'var_pop': 0.810658290414194}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 6,
             'name': 'stats__InjectionPressureMax__val',
             'value': {'avg': 39.537370569911104,
                       'count': 9.0,
                       'max': 44.0884060904,
                       'min': 35.4952094968,
                       'var_pop': 5.452849234986407}},
            {'asset': 'JB_HM_Diecast_1',
             'd_pos': 7,
             'name': 'stats__InjectionPressureMin__val',
             'value': {'avg': 36.76283137485556,
                       'count': 9.0,
                       'max': 38.8721003798,
                       'min': 35.0169147198,
                       'var_pop': 1.2194962602188073}}],
 'outcomes': [{'asset': 'JB_HM_Diecast_1',
               'd_pos': 0,
               'kpi': {'aggregates': {'Output': 'sum', 'ScrapQuantity': 'sum'},
                       'dependencies': {'Output': 9.0, 'ScrapQuantity': 0.0},
                       'formula': '((Output) / (Output + ScrapQuantity)) * 100 '
                                  'if ((Output + ScrapQuantity) > 0) else '
                                  'None'},
               'name': 'quality',
               'value': {'avg': 100.0,
                         'count': 100.0,
                         'max': 100.0,
                         'min': 100.0,
                         'normal': 1.0000000000000002,
                         'var_pop': 100.0}}]}]
}

CURRENT_VALUE = [{'asset': 'test', 'name': 'test_field', 'values': {'latest': 42.42}}]